# Numpy Exercises

In [1]:
import numpy as np

In [2]:
# Create a null vector of size 10
x=np.zeros(10)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
# Create a null vector of size 10 but the fifth value which is 1
x=np.zeros(10)
x[4]=1
x

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [4]:
# Create a vector with values ranging from 10 to 49 
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# Reverse a vector (first element becomes last) 
x=x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [6]:
# Create a 3x3 matrix with values ranging from 0 to 8
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
x=np.array([1,2,0,0,4,0])
x=np.nonzero(x)
x

(array([0, 1, 4], dtype=int64),)

In [13]:
# Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
x

array([[[ 0.89580464,  0.33709399,  0.17471185],
        [ 0.34395874,  0.35216671,  0.10517296],
        [ 0.333108  ,  0.67073753,  0.28347465]],

       [[ 0.2057605 ,  0.86802739,  0.61316858],
        [ 0.6564909 ,  0.35152483,  0.3035857 ],
        [ 0.26209781,  0.38054241,  0.5217456 ]],

       [[ 0.12740663,  0.59873661,  0.5745017 ],
        [ 0.49140524,  0.10461426,  0.84026015],
        [ 0.20441059,  0.86036835,  0.34643854]]])

In [17]:
# Create a 10x10 array with random values and find the minimum and maximum values
x=np.random.random((10,10))
print('max is ',np.max(x))
print('min is ',np.min(x))

max is  0.998755420555
min is  0.00417910456152


In [18]:
# Create a random vector of size 30 and find the mean value
x=np.random.random(30)
print('mean is ',np.mean(x))

mean is  0.433200857053


In [20]:
Z = np.ones((10,10))
Z[0:-1]


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [25]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
x=np.arange(10)
x[2]=-x[2]
x

array([ 0,  1, -2,  3,  4,  5,  6,  7,  8,  9])

In [26]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


False
False


In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
a=np.array([1,2,3])
x=np.repeat(a,3)
x

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
x = np.array([1,2,3])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3])

In [41]:
# Common values between two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [42]:
# return indexes where values are common
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [48]:
# Get all items between 5 and 10 from a.
a=np.arange(15)
#a[(a>=5) & (a<=10)]
np.where((a>=5) & (a<=10))

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

In [50]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [51]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
np.any(a>3)

True

In [58]:
c=[3,6,0]
a[c]

array([99,  6,  0])

In [61]:
a.sort()
a

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 99])

In [63]:
a[::-1]

array([99, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  2,  1,  0])

In [68]:
# Write a Python program to generate six random integers between 10 and 30
a=np.random.randint(10,30,6)
a

array([27, 23, 19, 26, 18, 29])

In [72]:
# Write a Python program to create a random 10x4 array and extract the first five rows of the array
a=np.random.random((10,4))
a[0:6,]

array([[ 0.63781013,  0.78414978,  0.36976499,  0.84842058],
       [ 0.87698245,  0.61469805,  0.49567881,  0.0822691 ],
       [ 0.68223345,  0.47780823,  0.819737  ,  0.60364182],
       [ 0.1474939 ,  0.18838531,  0.37615021,  0.45523363],
       [ 0.1392291 ,  0.56363909,  0.92215491,  0.12728373],
       [ 0.28312608,  0.76973159,  0.29109685,  0.39987734]])

In [74]:
# drop na values
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([ 1.,  2.,  3.,  5.,  6.,  7.])